server/src/main/java/com/gigker/server/domain/content/entity/ContentApply.java
server/src/main/java/com/gigker/server/domain/member/entity/Member.java
server/src/main/java/com/gigker/server/global/config/P6SpySqlFormatter.java
server/src/main/resources/application.yml

- 💡 Issue(#11)
- 엔티티 연관 관계 오류 수정
- P6spy 추가 (Sql 쿼리문에 실제 값이 들어가서 가독성을 올리기 위한 설정)
- 기타 설정 변경에 따른 application.yml 파일 수정
- 충돌 조심..

[feat / fix] 운영 서버 구축 과정에서 버그 수정 / 일부 설정 추가 및 수정

---

server/src/main/java/com/gigker/server/domain/member/controller/MemberController.java
server/src/main/java/com/gigker/server/domain/member/dto/MemberPostDto.java
server/src/main/java/com/gigker/server/domain/member/entity/Member.java
server/src/main/java/com/gigker/server/domain/member/entity/Profile.java
server/src/main/java/com/gigker/server/domain/member/mapper/MemberMaper.java
server/src/main/java/com/gigker/server/domain/member/mapper/ProfileMaper.java
server/src/main/java/com/gigker/server/domain/member/repository/MemberRepository.java
server/src/main/java/com/gigker/server/domain/member/repository/ProfileRepository.java
server/src/main/java/com/gigker/server/domain/member/service/MemberService.java
server/src/main/java/com/gigker/server/global/exception/ExceptionCode.java
server/src/test/java/com/gigker/server/ServerApplicationTests.java

- 💡 Issue(#14)
- 중복 예외 처리
- 가입시 프로필 정보 생성 및 연동
- 유효성 검사
- Exception Code 409 추가

[MEMBER] 회원가입

---

server/src/main/java/com/gigker/server/domain/content/service/ContentApplyService.java
server/src/main/java/com/gigker/server/domain/member/controller/MemberController.java
server/src/main/java/com/gigker/server/domain/member/service/MemberService.java

[MEMBER] 회원조회 메서드

---

server/build.gradle
server/src/main/java/com/gigker/server/domain/content/mapper/ContentMapper.java
server/src/main/java/com/gigker/server/domain/member/controller/MemberController.java
server/src/main/java/com/gigker/server/domain/member/dto/MemberPostDto.java
server/src/main/java/com/gigker/server/domain/member/entity/Member.java
server/src/main/java/com/gigker/server/domain/member/mapper/MemberMapper.java
server/src/main/java/com/gigker/server/domain/member/mapper/ProfileMapper.java
server/src/main/java/com/gigker/server/domain/member/service/MemberService.java
server/src/main/java/com/gigker/server/domain/review/mapper/ReviewMapper.java
server/src/main/java/com/gigker/server/global/s3/config/S3Config.java
server/src/main/java/com/gigker/server/global/s3/service/S3Service.java
server/src/main/resources/application.properties
server/src/main/resources/application.yml

- 💡 Issue(#16 )(#32)
- 회원가입시 이미지파일을 받으면 S3저장소에 저장
- 해당멤버의 DB에 이미지URL 저장
- MemberController 수정
- MemberPostDto 수정
- gradle.build에 AWS S3 설정
- global폴더안에 S3로직 추가
- application.properties 추가(환경변수 설정할꺼라 내용 넣지않았습니다.)
- MemberMapper 클래스 명 변경
- propertis -> yml파일로 통합 (아직 환경변수 설정 전이라 accessKey, secretKey, bucket 값을 넣지 않았습니다.)
- 저장소에 파일명 -> UUID.v4로 저장되게 하였습니다.
포스트맨으로 테스트 하였습니다. 
S3서버에 저장된 사진(파일명 -> UUID.v4명으로 저장됩니다.)
DB에 사용자의 URL컬럼에 S3의 URL주소가 저장된 사진

[MEMBER]회원가입 이미지 서버 구축 및 DB URL저장

---

server/src/main/java/com/gigker/server/domain/member/controller/MemberController.java
server/src/main/java/com/gigker/server/domain/member/dto/MemberPatchDto.java
server/src/main/java/com/gigker/server/domain/member/mapper/MemberMapper.java
server/src/main/java/com/gigker/server/domain/member/service/MemberService.java
server/src/main/java/com/gigker/server/global/exception/ExceptionCode.java
server/src/main/java/com/gigker/server/global/s3/service/S3Service.java
server/src/main/resources/application.yml

- 💡 Issue(#31)
- 로그인 했을 시 헤더로 토큰값을 받아올 수 있습니다.
- 로그인한 사용자만 회원 수정 가능하도록 추가하였습니다.
- 이미지 수정시 S3서버에 원래있던 사진파일이 삭제되고 수정된 이미지가 재 저장 됩니다.
효병님과(회원가입,로그인) 통신테스트 목적으로 컨트롤러 수정이 안된 상태에서 올립니다.

[MEMBER] 로그인 및 프로필 수정기능

---

client/src/components/Buttons.tsx
client/src/components/signup/SignUpForm.tsx
client/src/util/reducer.ts
client/src/util/store.ts
client/src/util/types.ts

회원가입 페이지 구현

---

client/src/components/hire/HireDropDown.tsx
client/src/components/hunting/CardProps.tsx
client/src/components/hunting/HuntingArticle.tsx
client/src/pages/Hunting.tsx

- 💡 Issue(#36 )
-전체구직페이지 데이터연결 세팅

feat:전체구직페이지데이터연결 및 오류수정

---

server/src/main/java/com/gigker/server/ServerApplication.java
server/src/main/java/com/gigker/server/domain/common/WorkTimeMapper.java
server/src/main/java/com/gigker/server/domain/common/WorkTimeResponseDto.java
server/src/main/java/com/gigker/server/domain/content/controller/ContentApplyController.java
server/src/main/java/com/gigker/server/domain/content/dto/ContentApplyResponseDto.java
server/src/main/java/com/gigker/server/domain/content/dto/ContentResponseDto.java
server/src/main/java/com/gigker/server/domain/content/entity/Content.java
server/src/main/java/com/gigker/server/domain/content/entity/ContentApply.java
server/src/main/java/com/gigker/server/domain/content/mapper/ContentApplyMapper.java
server/src/main/java/com/gigker/server/domain/content/mapper/ContentMapper.java
server/src/main/java/com/gigker/server/domain/content/repository/ContentApplyRepository.java
server/src/main/java/com/gigker/server/domain/content/repository/ContentRepository.java
server/src/main/java/com/gigker/server/domain/content/service/ContentApplyService.java
server/src/main/java/com/gigker/server/domain/content/service/ContentService.java
server/src/main/java/com/gigker/server/domain/member/dto/MemberProfileResponseDto.java
server/src/main/java/com/gigker/server/domain/member/entity/Member.java
server/src/main/java/com/gigker/server/domain/member/entity/Profile.java
server/src/main/java/com/gigker/server/domain/member/mapper/MemberMapper.java
server/src/main/java/com/gigker/server/domain/review/controller/ReviewController.java
server/src/main/java/com/gigker/server/domain/review/dto/ReviewDto.java
server/src/main/java/com/gigker/server/domain/review/mapper/ReviewMapper.java
server/src/main/java/com/gigker/server/domain/review/service/ReviewService.java
server/src/main/resources/data.sql
server/src/test/java/com/gigker/server/domain/stub/ContentStubData.java

- 💡 Issue(#60 )
- data.sql의 변수명 수정
- Scheduled 어노테이션 적용
- 지원자 작업 완료 시점에 상태를 변경하는 로직 + 게시글 상태 변경 로직 추가 (테스트 어려움 실제 동작하는지 확인 X)
- 게시글 Deadline 시점에 상태를 변경하는 로직 추가 (테스트 어려움 실제 동작하는지 확인 X)
- 멤버 Review 정보를 가져오는 로직 구현 (DDD)
- 지원 요청 시 지원에 대한 정보를 반환하도록 수정
- 전체 게시글 조회 및 지원자 정보 조회 오류 수정
- 지원 요청 시 Response 반환하도록 수정
- Review 작성 시 Response 반환하도록 수정
- SimpleMemberResponse 경로 수정 (MemberProfileResponseDto -> ReviewDto)

[ContentApply] 모집 만료 및 작업 완료 시 상태를 변경하는 로직 추가

---

client/src/App.tsx
client/src/components/CateLocaTag.tsx
client/src/components/TimeSelect.tsx
client/src/components/hire/CardProps.tsx
client/src/components/hire/HireArticle.tsx
client/src/components/hunting/CardProps.tsx
client/src/components/hunting/HuntingArticle.tsx
client/src/pages/EditHire.tsx
client/src/pages/EditHunting.tsx
client/src/pages/NewHire.tsx
client/src/pages/NewHunting.tsx

- 💡 Issue(#37 )
-새글작성post 에러 1차수정
-error 메시지 부분 수정

NewHire,Hunting

---

client/package-lock.json
client/package.json
client/src/App.tsx
client/src/components/Navigation.tsx
client/src/components/login/LogInForm.tsx
client/src/components/signup/SignUpForm.tsx
client/src/index.tsx
client/src/util/cookie/index.ts
client/src/util/logInApi.ts

- 💡 Issue(#81 )
- 로그인 & 로그아웃
- access토큰 10분
- refresh토큰 1일
- 페이지 새로고침시 로그인 연장

로그인 & 로그아웃 기능 구현

---

client/src/components/TimeSelect.tsx
client/src/components/hire/HireArticle.tsx
client/src/components/hire/HireDropDown.tsx
client/src/components/hunting/HuntingArticle.tsx
client/src/components/hunting/HuntingDropDown.tsx
client/src/components/login/LogInForm.tsx
client/src/components/signup/SignUpForm.tsx
client/src/pages/NewHire.tsx
client/src/pages/NewHunting.tsx

- 💡 Issue(#37 )
- 데드라인 추가 및 서버주소변경

fix:data passing 오류부분 수정

---

server/build.gradle
server/src/main/java/com/gigker/server/domain/member/mapper/ProfileMapper.java
server/src/main/java/com/gigker/server/global/config/SecurityConfiguration.java
server/src/main/resources/application.yml
server/src/test/java/com/gigker/server/domain/stub/ContentStubData.java

프론트에서 Refresh Header가 보이지않는 이슈 해결
- cors설정에서 Refresh Header를 추가 하였습니다.
- profile mapper에서 초기값 세팅을 추가 하였습니다.
- yml파일에 주석을 추가 하였습니다.

[MEMBER] 프론트에서 Refresh Header가 보이지않는 이슈 해결

---

client/src/components/hire/CardProps.tsx
client/src/components/hire/HireArticle.tsx
client/src/components/hire/HireDropDown.tsx
client/src/components/hunting/CardProps.tsx
client/src/components/hunting/HuntingArticle.tsx
client/src/components/hunting/HuntingDropDown.tsx
client/src/pages/NewHunting.tsx

- 💡 Issue(#9 )
- 전체구인구직 카드UI 오류수정
- 전체구인구직 버튼CSS 수정

Hire,Hunting

---

client/src/components/hunting/HuntingArticle.tsx

style:오타수정

---

client/src/App.tsx
client/src/pages/EditHire.tsx
client/src/pages/HireDetail.tsx

feat:edithire 기능구현1차

---

client/package-lock.json
client/package.json
client/src/App.tsx
client/src/components/Navigation.tsx
client/src/components/schedule/Calendar.tsx
client/src/components/schedule/CalendarSide.tsx
client/src/components/schedule/event-utils.tsx
client/src/pages/Schedule.tsx
client/src/util/redux/CalendarEvents.ts
client/src/util/redux/index.ts

- 💡 Issue(#112 )
- 달력 api 사용해서 목업 페이지 구현

feat/ 스케줄페이지 목업 구현 & 라우팅

---

client/src/pages/EditHire.tsx
client/src/pages/EditHunting.tsx
client/src/pages/HuntingDetail.tsx

- edit 시 발생하는 오류 수정
- hunting edit 페이지 설정

fix:editing 기능 수정

---

client/src/pages/EditHire.tsx
client/src/pages/EditHunting.tsx
client/src/pages/NewHire.tsx
client/src/pages/NewHunting.tsx

- 새글, 수정글 작성, 삭제 시 navigate 연결

fix:새글작성,수정완료시navigate연결

---

client/src/pages/EditHire.tsx
client/src/pages/EditHunting.tsx
client/src/pages/NewHire.tsx
client/src/pages/NewHunting.tsx

- 카테고리,지역 선택오류 수정
- 불필요한 코드 삭제

fix:카테고리,지역설정오류수정

---

client/src/components/TimeSelect.tsx
client/src/components/hire/HireArticle.tsx
client/src/components/hire/HireDropDown.tsx
client/src/components/hunting/HuntingArticle.tsx
client/src/components/hunting/HuntingDropDown.tsx
client/src/pages/EditHire.tsx
client/src/pages/EditHunting.tsx
client/src/pages/NewHire.tsx
client/src/pages/NewHunting.tsx

- 콘솔로그 삭제
- 글 작성시 미작성 부분 있을 시 alert 추가

style:로그삭제 및 alert기능추가

---

client/src/assets/styles/global-styles.tsx
client/src/components/Navigation.tsx
client/src/components/hire/HireDropDown.tsx
client/src/components/login/LogInForm.tsx
client/src/components/mypage/EditForm.tsx
client/src/components/mypage/MyPageDetail.tsx
client/src/util/logInApi.ts

- 💡 Issue(#)
- 로그인 시 두번 깜박이는 문제 수정
- 구인페이지 css 1차 수정

로그인 시 두번 깜박이는 문제 수정

---

client/src/assets/styles/global-styles.tsx
client/src/components/Buttons.tsx
client/src/components/Navigation.tsx
client/src/components/hire/HireDropDown.tsx
client/src/components/hunting/HuntingDropDown.tsx
client/src/components/login/LogInForm.tsx
client/src/components/signup/SignUpForm.tsx
client/src/pages/LogInPage.tsx
client/src/pages/SignUpPage.tsx

- 💡 Issue(#126 )
- nav 바 양쪽여백
- a > button 수정 -> a로만
- 버튼 호버 default, a 호버 pointer
- 로그인, 가입페이지 상단 margin 통일
- y축 스크롤 여부에따라 레이아웃 깨짐 -> overflow-y: scroll로 항상 스크롤 설정
- 소셜로그인 삭제 -> (논의)
- label 연결 안된거 오타 수정
- line-height: 1.4
- 구인, 구직 페이지 통일
- 드롭다운 스크롤, 호버, 높이, 색 변경

[Style] CSS 수정

---

client/src/components/hire/HireArticle.tsx
client/src/components/hire/HireDropDown.tsx
client/src/components/hunting/HuntingArticle.tsx
client/src/util/redux/DropDown.ts

- 💡 Issue(#36 )
- fix: 구인구직 카테고리 선택 유지되는거 해제

fix: 드롭다운 리셋기능 추가

---

client/src/components/TimeSelect.tsx
client/src/pages/EditHire.tsx
client/src/pages/EditHunting.tsx
client/src/pages/NewHire.tsx
client/src/pages/NewHunting.tsx

style: 새글,수정글 작성페이지 CSS수정

---

server/src/main/java/com/gigker/server/domain/review/controller/ReviewController.java
server/src/main/java/com/gigker/server/domain/review/dto/ReviewDto.java
server/src/main/java/com/gigker/server/domain/review/entity/Review.java
server/src/main/java/com/gigker/server/domain/review/mapper/ReviewMapper.java
server/src/main/java/com/gigker/server/domain/review/service/ReviewService.java

- Response 누락된 부분 추가 및 수정
- 단일 리뷰 조회 시 작성자 닉네임 포함되도록 추가
- 리뷰 작성 시 작성자 정보 누락된 부분 수정

[Review] Response 누락된 부분 추가 및 수정

---

client/src/components/hire/CardProps.tsx
client/src/components/hire/HireArticle.tsx
client/src/components/hunting/CardProps.tsx
client/src/components/hunting/HuntingArticle.tsx
client/src/pages/EditHire.tsx
client/src/pages/EditHunting.tsx

- CSS 통일
- 전체구인,구직페이지 최신순정렬 세팅

style: edit 페이지 CSS통일, 전체구직구인최신순정렬

---

client/src/pages/EditHire.tsx
client/src/pages/EditHunting.tsx
client/src/pages/NewHire.tsx
client/src/pages/NewHunting.tsx

fix: 새글작성,수정 시 숫자작성 음수만 가능하게 수정

---

client/src/components/hire/HireArticle.tsx
client/src/components/hunting/HuntingArticle.tsx

fix: 전체 구인구직 코드오류수정

---

client/src/components/hire/HireArticle.tsx
client/src/components/hunting/HuntingArticle.tsx

- 💡 Issue(#9 )
- 최신순 정렬 (두번 클릭해야 하는 오류 수정)

fix: sorting 기능 수정

---

server/src/main/java/com/gigker/server/domain/content/controller/ContentApplyController.java
server/src/main/java/com/gigker/server/domain/content/service/ContentApplyService.java
server/src/main/java/com/gigker/server/domain/review/controller/ReviewController.java
server/src/main/java/com/gigker/server/domain/review/service/ReviewService.java
server/src/main/java/com/gigker/server/domain/schedule/controller/ScheduleController.java
server/src/main/java/com/gigker/server/domain/schedule/service/ScheduleService.java
server/src/main/java/com/gigker/server/global/exception/ExceptionCode.java
server/src/test/java/com/gigker/server/domain/contentApply/ContentApplyServiceTest.java
server/src/test/java/com/gigker/server/domain/contentApply/ContentApplyValidationUnitTest.java
server/src/test/java/com/gigker/server/domain/stub/ContentApplyStubData.java
server/src/test/java/com/gigker/server/domain/stub/ContentStubData.java

- 💡 Issue(#124 )
- Junit과 Mockito를 사용한 테스트 코드 리팩터링
- 테스트 코드 작성 하다가 느낀건데..   
Service 로직에서 getCurrentMember()를 사용하는 것이 아닌 Controller에서 MemberService를 통해 인증 정보를 가져와서 서비스 로직으로 Member.class를 넘겨주는게 테스트하기에 훨씬 좋은 코드인 것 같습니다.

[ContentApplyTest] 테스트 코드 리팩터링

---

server/src/main/java/com/gigker/server/domain/content/controller/ContentController.java
server/src/main/java/com/gigker/server/domain/content/dto/ContentResponseDto.java
server/src/main/java/com/gigker/server/domain/content/mapper/ContentMapper.java

- 전체 게시글 조회 시 SimpleResponse를 반환하도록 변경
- SimpleResponse에 지역 정보, 카테고리 정보, 태그 정보, createdAt, lastModifiedAt 추가

[Content] 전체 게시글 조회 시 정보 누락된 부분 수정

---

client/src/pages/EditHire.tsx
client/src/pages/EditHunting.tsx

fix: 수정시 일부 데이터 미입력 오류 수정

---

client/src/pages/EditHire.tsx
client/src/pages/EditHunting.tsx

fix: edit 시 태그 데이터 불러오기

---

server/src/main/java/com/gigker/server/domain/content/dto/ContentPatchDto.java
server/src/main/java/com/gigker/server/domain/content/dto/ContentPostDto.java
server/src/main/java/com/gigker/server/domain/content/dto/ContentResponseDto.java

- Contents Response에 content Type 추가
-

Content Response 수정

---

server/src/main/java/com/gigker/server/domain/content/repository/ContentRepository.java
server/src/main/java/com/gigker/server/domain/content/service/ContentApplyService.java
server/src/main/java/com/gigker/server/domain/content/service/ContentService.java
server/src/main/java/com/gigker/server/domain/expired/ExpiredService.java

- 💡 Issue(#157 )
- ContentService 및 ContentApplyService에 있던 Scheduler 로직을 별도의 서비스 로직으로 분리
- 기존 set을 사용해 더티 체킹이 발생하던 부분을 수정하여 쿼리문이 한 개로 나올 수 있도록 수정

[Expired] 만료 및 완료 시키는 로직 분리 + 리팩터링

---

client/src/api/getDatas.ts
client/src/api/getDetail.ts
client/src/api/getMember.ts
client/src/api/getReivew.ts
client/src/components/Navigation.tsx
client/src/components/hire/HireArticle.tsx
client/src/components/hunting/HuntingArticle.tsx
client/src/components/login/LogInForm.tsx
client/src/components/mypage/EditForm.tsx
client/src/components/mypage/MyPageDetail.tsx
client/src/components/signup/SignUpForm.tsx
client/src/pages/EditHire.tsx
client/src/pages/EditHunting.tsx
client/src/pages/HireDetail.tsx
client/src/pages/HuntingDetail.tsx
client/src/pages/NewHire.tsx
client/src/pages/NewHunting.tsx

- https api백엔드서버 적용으로 인한 프론트에서 연결된 api주소 변경
- 프론트 S3주소 https로 적용

gigker 프론트 , 백엔드API서버 https적용
